<?php

namespace HubletoApp\Community\Discussions\Controllers;

class Members extends \HubletoMain\Core\Controllers\Controller
{

  // Uncomment this if you want to make your controller public
  // public bool $requiresUserAuthentication = false;

  // Uncomment this if you want to have full control over the response content
  // (default Hubleto's desktop will not be rendered)
  // public bool $hideDefaultDesktop = true;

  public function prepareView(): void
  {

    // Uncomment this if you want your controller be hookable
    // $this->main->hooks->run('controller:prepare-view-start', [$this]);

    parent::prepareView();

    // these parameters are generated by the `php hubleto` command
    $this->viewParams['now'] = date('Y-m-d H:i:s');
    $this->viewParams['randomNumber'] = rand(1, 1000);

    $this->setView('@HubletoApp:Community:Discussions/Members.twig');

    // Uncomment this if you want your controller be hookable
    // $this->main->hooks->run('controller:prepare-view-end', [$this]);
  }

}
