import BillingTableBillingAccountService from "./Components/TableBillingAccountServices"

globalThis.main.registerReactComponent('BillingTableBillingAccountService', BillingTableBillingAccountService);
