namespace: HubletoApp\Community\Tasks
sidebarGroup: tasks
rootUrlSlug: tasks
name: Tasks
icon: fas fa-list-check
author:
  name: "WAI.blue"
  nick: "wai.blue"
highlight: Task management app
created: 2025-06-25 18:55:11