<?php

namespace HubletoApp\Community\Tasks\Controllers;

class Tasks extends \HubletoMain\Core\Controllers\Controller
{

  public function prepareView(): void
  {
    parent::prepareView();

    // these parameters are generated by the `php hubleto` command
    $this->viewParams['now'] = date('Y-m-d H:i:s');
    $this->viewParams['randomNumber'] = rand(1, 1000);

    $this->setView('@HubletoApp:Community:Tasks/Tasks.twig');
  }

}
